/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) qp_gradJ_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Printing routine */
#define PRINTF printf

static const int casadi_s0[144] = {140, 1, 0, 140, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139};
static const int casadi_s1[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const int casadi_s2[82] = {140, 1, 0, 78, 0, 1, 3, 5, 7, 8, 10, 12, 14, 15, 17, 19, 21, 22, 24, 26, 28, 29, 31, 33, 35, 36, 38, 40, 42, 43, 45, 47, 49, 50, 52, 54, 56, 57, 59, 61, 63, 64, 66, 68, 70, 71, 73, 75, 77, 78, 80, 82, 84, 85, 87, 89, 91, 92, 94, 96, 98, 99, 101, 103, 105, 106, 108, 110, 112, 113, 115, 117, 119, 120, 122, 124, 126, 127, 129, 131, 133, 134};

void casadi_fill(casadi_real* x, int n, casadi_real alpha) {
  int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, int n, casadi_real* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

/* adj1_fJDisc:(i0[5],i1[2],i2[2],i3[4],out_o0[1x1,0nz],adj_o0)->(adj_i0[5],adj_i1[2],adj_i2[2],adj_i3[4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1, w2, *w3=w+7, w4, w5, *w6=w+14, w7, w8, *w9=w+18, w10, w11, w12;
  /* #0: @0 = zeros(5x1) */
  casadi_fill(w0, 5, 0.);
  /* #1: @1 = 4.32115 */
  w1 = 4.3211476968282776e+000;
  /* #2: @2 = 1 */
  w2 = 1.;
  /* #3: @3 = input[0][0] */
  casadi_copy(arg[0], 5, w3);
  /* #4: @4 = @3[3] */
  for (rr=(&w4), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #5: @5 = 0.23142 */
  w5 = 2.3141999999999999e-001;
  /* #6: @4 = (@4/@5) */
  w4 /= w5;
  /* #7: @2 = (@2-@4) */
  w2 -= w4;
  /* #8: @6 = input[2][0] */
  casadi_copy(arg[2], 2, w6);
  /* #9: @4 = @6[1] */
  for (rr=(&w4), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #10: @2 = (@2-@4) */
  w2 -= w4;
  /* #11: @4 = (2.*@2) */
  w4 = (2.* w2 );
  /* #12: @5 = input[3][1] */
  w5 = arg[3] ? arg[3][1] : 0;
  /* #13: @7 = input[5][0] */
  w7 = arg[5] ? arg[5][0] : 0;
  /* #14: @5 = (@5*@7) */
  w5 *= w7;
  /* #15: @4 = (@4*@5) */
  w4 *= w5;
  /* #16: @1 = (@1*@4) */
  w1 *= w4;
  /* #17: @1 = (-@1) */
  w1 = (- w1 );
  /* #18: (@0[3] += @1) */
  for (rr=w0+3, ss=(&w1); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #19: @1 = @3[1] */
  for (rr=(&w1), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #20: @5 = @6[0] */
  for (rr=(&w5), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #21: @1 = (@1-@5) */
  w1 -= w5;
  /* #22: @5 = (2.*@1) */
  w5 = (2.* w1 );
  /* #23: @8 = input[3][0] */
  w8 = arg[3] ? arg[3][0] : 0;
  /* #24: @8 = (@8*@7) */
  w8 *= w7;
  /* #25: @5 = (@5*@8) */
  w5 *= w8;
  /* #26: (@0[1] += @5) */
  for (rr=w0+1, ss=(&w5); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #27: output[0][0] = @0 */
  casadi_copy(w0, 5, res[0]);
  /* #28: @6 = zeros(2x1) */
  casadi_fill(w6, 2, 0.);
  /* #29: @9 = input[1][0] */
  casadi_copy(arg[1], 2, w9);
  /* #30: @8 = @9[1] */
  for (rr=(&w8), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #31: @10 = (2.*@8) */
  w10 = (2.* w8 );
  /* #32: @11 = input[3][3] */
  w11 = arg[3] ? arg[3][3] : 0;
  /* #33: @11 = (@11*@7) */
  w11 *= w7;
  /* #34: @10 = (@10*@11) */
  w10 *= w11;
  /* #35: (@6[1] += @10) */
  for (rr=w6+1, ss=(&w10); rr!=w6+2; rr+=1) *rr += *ss++;
  /* #36: @10 = @9[0] */
  for (rr=(&w10), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #37: @11 = (2.*@10) */
  w11 = (2.* w10 );
  /* #38: @12 = input[3][2] */
  w12 = arg[3] ? arg[3][2] : 0;
  /* #39: @12 = (@12*@7) */
  w12 *= w7;
  /* #40: @11 = (@11*@12) */
  w11 *= w12;
  /* #41: (@6[0] += @11) */
  for (rr=w6+0, ss=(&w11); rr!=w6+1; rr+=1) *rr += *ss++;
  /* #42: output[1][0] = @6 */
  casadi_copy(w6, 2, res[1]);
  /* #43: @6 = zeros(2x1) */
  casadi_fill(w6, 2, 0.);
  /* #44: @4 = (-@4) */
  w4 = (- w4 );
  /* #45: (@6[1] += @4) */
  for (rr=w6+1, ss=(&w4); rr!=w6+2; rr+=1) *rr += *ss++;
  /* #46: @5 = (-@5) */
  w5 = (- w5 );
  /* #47: (@6[0] += @5) */
  for (rr=w6+0, ss=(&w5); rr!=w6+1; rr+=1) *rr += *ss++;
  /* #48: output[2][0] = @6 */
  casadi_copy(w6, 2, res[2]);
  /* #49: @1 = sq(@1) */
  w1 = sq( w1 );
  /* #50: @1 = (@1*@7) */
  w1 *= w7;
  /* #51: output[3][0] = @1 */
  if (res[3]) res[3][0] = w1;
  /* #52: @2 = sq(@2) */
  w2 = sq( w2 );
  /* #53: @2 = (@2*@7) */
  w2 *= w7;
  /* #54: output[3][1] = @2 */
  if (res[3]) res[3][1] = w2;
  /* #55: @10 = sq(@10) */
  w10 = sq( w10 );
  /* #56: @10 = (@10*@7) */
  w10 *= w7;
  /* #57: output[3][2] = @10 */
  if (res[3]) res[3][2] = w10;
  /* #58: @8 = sq(@8) */
  w8 = sq( w8 );
  /* #59: @8 = (@8*@7) */
  w8 *= w7;
  /* #60: output[3][3] = @8 */
  if (res[3]) res[3][3] = w8;
  return 0;
}

/* qp_gradJ:(i0[140],i1[13])->(o0[140x1,78nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+2, *cr, *cs;
  int i;
  casadi_real *w0=w+23, *w1=w+101, *w2=w+114, *w3=w+119, *w4=w+121, *w5=w+123, *w6=w+125, w8, *w9=w+130, *w10=w+132, *w11=w+137, w12;
  /* #0: @0 = zeros(140x1,78nz) */
  casadi_fill(w0, 78, 0.);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 13, w1);
  /* #2: @2 = @1[:5] */
  for (rr=w2, ss=w1+0; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #3: @3 = input[0][0] */
  casadi_copy(arg[0], 2, w3);
  /* #4: @4 = @1[5:7] */
  for (rr=w4, ss=w1+5; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #5: @4 = (@3-@4) */
  for (i=0, rr=w4, cr=w3, cs=w4; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #6: @5 = @1[7:9] */
  for (rr=w5, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #7: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #8: @7 = 00 */
  /* #9: @8 = 1 */
  w8 = 1.;
  /* #10: {NULL, @9, NULL, NULL} = adj1_fJDisc(@2, @4, @5, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w4;
  arg1[2]=w5;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=0;
  res1[1]=w9;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #11: @2 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+2 : 0, 5, w2);
  /* #12: @4 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 2, w4);
  /* #13: @3 = (@4-@3) */
  for (i=0, rr=w3, cr=w4, cs=w3; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #14: @5 = @1[7:9] */
  for (rr=w5, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #15: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #16: @7 = 00 */
  /* #17: {@10, @11, NULL, NULL} = adj1_fJDisc(@2, @3, @5, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w3;
  arg1[2]=w5;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w11;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: @9 = (@9-@11) */
  for (i=0, rr=w9, cs=w11; i<2; ++i) (*rr++) -= (*cs++);
  /* #19: @12 = @9[0] */
  for (rr=(&w12), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #20: (@0[0] = @12) */
  for (rr=w0+0, ss=(&w12); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #21: @12 = @9[1] */
  for (rr=(&w12), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #22: (@0[1] = @12) */
  for (rr=w0+1, ss=(&w12); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #23: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #24: (@0[2] = @12) */
  for (rr=w0+2, ss=(&w12); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #25: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #26: (@0[3] = @12) */
  for (rr=w0+3, ss=(&w12); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #27: @10 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 5, w10);
  /* #28: @9 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+14 : 0, 2, w9);
  /* #29: @4 = (@9-@4) */
  for (i=0, rr=w4, cr=w9, cs=w4; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #30: @3 = @1[7:9] */
  for (rr=w3, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #31: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #32: @7 = 00 */
  /* #33: {@2, @5, NULL, NULL} = adj1_fJDisc(@10, @4, @3, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w4;
  arg1[2]=w3;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w5;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #34: @11 = (@11-@5) */
  for (i=0, rr=w11, cs=w5; i<2; ++i) (*rr++) -= (*cs++);
  /* #35: @12 = @11[0] */
  for (rr=(&w12), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #36: (@0[4] = @12) */
  for (rr=w0+4, ss=(&w12); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #37: @12 = @11[1] */
  for (rr=(&w12), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #38: (@0[5] = @12) */
  for (rr=w0+5, ss=(&w12); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #39: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #40: (@0[6] = @12) */
  for (rr=w0+6, ss=(&w12); rr!=w0+7; rr+=1) *rr = *ss++;
  /* #41: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #42: (@0[7] = @12) */
  for (rr=w0+7, ss=(&w12); rr!=w0+8; rr+=1) *rr = *ss++;
  /* #43: @2 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+16 : 0, 5, w2);
  /* #44: @11 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 2, w11);
  /* #45: @9 = (@11-@9) */
  for (i=0, rr=w9, cr=w11, cs=w9; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #46: @4 = @1[7:9] */
  for (rr=w4, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #47: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #48: @7 = 00 */
  /* #49: {@10, @3, NULL, NULL} = adj1_fJDisc(@2, @9, @4, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w9;
  arg1[2]=w4;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w3;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #50: @5 = (@5-@3) */
  for (i=0, rr=w5, cs=w3; i<2; ++i) (*rr++) -= (*cs++);
  /* #51: @12 = @5[0] */
  for (rr=(&w12), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #52: (@0[8] = @12) */
  for (rr=w0+8, ss=(&w12); rr!=w0+9; rr+=1) *rr = *ss++;
  /* #53: @12 = @5[1] */
  for (rr=(&w12), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #54: (@0[9] = @12) */
  for (rr=w0+9, ss=(&w12); rr!=w0+10; rr+=1) *rr = *ss++;
  /* #55: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #56: (@0[10] = @12) */
  for (rr=w0+10, ss=(&w12); rr!=w0+11; rr+=1) *rr = *ss++;
  /* #57: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #58: (@0[11] = @12) */
  for (rr=w0+11, ss=(&w12); rr!=w0+12; rr+=1) *rr = *ss++;
  /* #59: @10 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+23 : 0, 5, w10);
  /* #60: @5 = input[0][8] */
  casadi_copy(arg[0] ? arg[0]+28 : 0, 2, w5);
  /* #61: @11 = (@5-@11) */
  for (i=0, rr=w11, cr=w5, cs=w11; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #62: @9 = @1[7:9] */
  for (rr=w9, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #63: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #64: @7 = 00 */
  /* #65: {@2, @4, NULL, NULL} = adj1_fJDisc(@10, @11, @9, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w11;
  arg1[2]=w9;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w4;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #66: @3 = (@3-@4) */
  for (i=0, rr=w3, cs=w4; i<2; ++i) (*rr++) -= (*cs++);
  /* #67: @12 = @3[0] */
  for (rr=(&w12), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #68: (@0[12] = @12) */
  for (rr=w0+12, ss=(&w12); rr!=w0+13; rr+=1) *rr = *ss++;
  /* #69: @12 = @3[1] */
  for (rr=(&w12), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #70: (@0[13] = @12) */
  for (rr=w0+13, ss=(&w12); rr!=w0+14; rr+=1) *rr = *ss++;
  /* #71: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #72: (@0[14] = @12) */
  for (rr=w0+14, ss=(&w12); rr!=w0+15; rr+=1) *rr = *ss++;
  /* #73: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #74: (@0[15] = @12) */
  for (rr=w0+15, ss=(&w12); rr!=w0+16; rr+=1) *rr = *ss++;
  /* #75: @2 = input[0][9] */
  casadi_copy(arg[0] ? arg[0]+30 : 0, 5, w2);
  /* #76: @3 = input[0][10] */
  casadi_copy(arg[0] ? arg[0]+35 : 0, 2, w3);
  /* #77: @5 = (@3-@5) */
  for (i=0, rr=w5, cr=w3, cs=w5; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #78: @11 = @1[7:9] */
  for (rr=w11, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #79: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #80: @7 = 00 */
  /* #81: {@10, @9, NULL, NULL} = adj1_fJDisc(@2, @5, @11, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w5;
  arg1[2]=w11;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w9;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #82: @4 = (@4-@9) */
  for (i=0, rr=w4, cs=w9; i<2; ++i) (*rr++) -= (*cs++);
  /* #83: @12 = @4[0] */
  for (rr=(&w12), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #84: (@0[16] = @12) */
  for (rr=w0+16, ss=(&w12); rr!=w0+17; rr+=1) *rr = *ss++;
  /* #85: @12 = @4[1] */
  for (rr=(&w12), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #86: (@0[17] = @12) */
  for (rr=w0+17, ss=(&w12); rr!=w0+18; rr+=1) *rr = *ss++;
  /* #87: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #88: (@0[18] = @12) */
  for (rr=w0+18, ss=(&w12); rr!=w0+19; rr+=1) *rr = *ss++;
  /* #89: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #90: (@0[19] = @12) */
  for (rr=w0+19, ss=(&w12); rr!=w0+20; rr+=1) *rr = *ss++;
  /* #91: @10 = input[0][11] */
  casadi_copy(arg[0] ? arg[0]+37 : 0, 5, w10);
  /* #92: @4 = input[0][12] */
  casadi_copy(arg[0] ? arg[0]+42 : 0, 2, w4);
  /* #93: @3 = (@4-@3) */
  for (i=0, rr=w3, cr=w4, cs=w3; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #94: @5 = @1[7:9] */
  for (rr=w5, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #95: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #96: @7 = 00 */
  /* #97: {@2, @11, NULL, NULL} = adj1_fJDisc(@10, @3, @5, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w3;
  arg1[2]=w5;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w11;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #98: @9 = (@9-@11) */
  for (i=0, rr=w9, cs=w11; i<2; ++i) (*rr++) -= (*cs++);
  /* #99: @12 = @9[0] */
  for (rr=(&w12), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #100: (@0[20] = @12) */
  for (rr=w0+20, ss=(&w12); rr!=w0+21; rr+=1) *rr = *ss++;
  /* #101: @12 = @9[1] */
  for (rr=(&w12), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #102: (@0[21] = @12) */
  for (rr=w0+21, ss=(&w12); rr!=w0+22; rr+=1) *rr = *ss++;
  /* #103: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #104: (@0[22] = @12) */
  for (rr=w0+22, ss=(&w12); rr!=w0+23; rr+=1) *rr = *ss++;
  /* #105: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #106: (@0[23] = @12) */
  for (rr=w0+23, ss=(&w12); rr!=w0+24; rr+=1) *rr = *ss++;
  /* #107: @2 = input[0][13] */
  casadi_copy(arg[0] ? arg[0]+44 : 0, 5, w2);
  /* #108: @9 = input[0][14] */
  casadi_copy(arg[0] ? arg[0]+49 : 0, 2, w9);
  /* #109: @4 = (@9-@4) */
  for (i=0, rr=w4, cr=w9, cs=w4; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #110: @3 = @1[7:9] */
  for (rr=w3, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #111: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #112: @7 = 00 */
  /* #113: {@10, @5, NULL, NULL} = adj1_fJDisc(@2, @4, @3, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w4;
  arg1[2]=w3;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w5;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #114: @11 = (@11-@5) */
  for (i=0, rr=w11, cs=w5; i<2; ++i) (*rr++) -= (*cs++);
  /* #115: @12 = @11[0] */
  for (rr=(&w12), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #116: (@0[24] = @12) */
  for (rr=w0+24, ss=(&w12); rr!=w0+25; rr+=1) *rr = *ss++;
  /* #117: @12 = @11[1] */
  for (rr=(&w12), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #118: (@0[25] = @12) */
  for (rr=w0+25, ss=(&w12); rr!=w0+26; rr+=1) *rr = *ss++;
  /* #119: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #120: (@0[26] = @12) */
  for (rr=w0+26, ss=(&w12); rr!=w0+27; rr+=1) *rr = *ss++;
  /* #121: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #122: (@0[27] = @12) */
  for (rr=w0+27, ss=(&w12); rr!=w0+28; rr+=1) *rr = *ss++;
  /* #123: @10 = input[0][15] */
  casadi_copy(arg[0] ? arg[0]+51 : 0, 5, w10);
  /* #124: @11 = input[0][16] */
  casadi_copy(arg[0] ? arg[0]+56 : 0, 2, w11);
  /* #125: @9 = (@11-@9) */
  for (i=0, rr=w9, cr=w11, cs=w9; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #126: @4 = @1[7:9] */
  for (rr=w4, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #127: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #128: @7 = 00 */
  /* #129: {@2, @3, NULL, NULL} = adj1_fJDisc(@10, @9, @4, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w9;
  arg1[2]=w4;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w3;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #130: @5 = (@5-@3) */
  for (i=0, rr=w5, cs=w3; i<2; ++i) (*rr++) -= (*cs++);
  /* #131: @12 = @5[0] */
  for (rr=(&w12), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #132: (@0[28] = @12) */
  for (rr=w0+28, ss=(&w12); rr!=w0+29; rr+=1) *rr = *ss++;
  /* #133: @12 = @5[1] */
  for (rr=(&w12), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #134: (@0[29] = @12) */
  for (rr=w0+29, ss=(&w12); rr!=w0+30; rr+=1) *rr = *ss++;
  /* #135: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #136: (@0[30] = @12) */
  for (rr=w0+30, ss=(&w12); rr!=w0+31; rr+=1) *rr = *ss++;
  /* #137: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #138: (@0[31] = @12) */
  for (rr=w0+31, ss=(&w12); rr!=w0+32; rr+=1) *rr = *ss++;
  /* #139: @2 = input[0][17] */
  casadi_copy(arg[0] ? arg[0]+58 : 0, 5, w2);
  /* #140: @5 = input[0][18] */
  casadi_copy(arg[0] ? arg[0]+63 : 0, 2, w5);
  /* #141: @11 = (@5-@11) */
  for (i=0, rr=w11, cr=w5, cs=w11; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #142: @9 = @1[7:9] */
  for (rr=w9, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #143: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #144: @7 = 00 */
  /* #145: {@10, @4, NULL, NULL} = adj1_fJDisc(@2, @11, @9, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w11;
  arg1[2]=w9;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w4;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #146: @3 = (@3-@4) */
  for (i=0, rr=w3, cs=w4; i<2; ++i) (*rr++) -= (*cs++);
  /* #147: @12 = @3[0] */
  for (rr=(&w12), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #148: (@0[32] = @12) */
  for (rr=w0+32, ss=(&w12); rr!=w0+33; rr+=1) *rr = *ss++;
  /* #149: @12 = @3[1] */
  for (rr=(&w12), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #150: (@0[33] = @12) */
  for (rr=w0+33, ss=(&w12); rr!=w0+34; rr+=1) *rr = *ss++;
  /* #151: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #152: (@0[34] = @12) */
  for (rr=w0+34, ss=(&w12); rr!=w0+35; rr+=1) *rr = *ss++;
  /* #153: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #154: (@0[35] = @12) */
  for (rr=w0+35, ss=(&w12); rr!=w0+36; rr+=1) *rr = *ss++;
  /* #155: @10 = input[0][19] */
  casadi_copy(arg[0] ? arg[0]+65 : 0, 5, w10);
  /* #156: @3 = input[0][20] */
  casadi_copy(arg[0] ? arg[0]+70 : 0, 2, w3);
  /* #157: @5 = (@3-@5) */
  for (i=0, rr=w5, cr=w3, cs=w5; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #158: @11 = @1[7:9] */
  for (rr=w11, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #159: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #160: @7 = 00 */
  /* #161: {@2, @9, NULL, NULL} = adj1_fJDisc(@10, @5, @11, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w5;
  arg1[2]=w11;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w9;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #162: @4 = (@4-@9) */
  for (i=0, rr=w4, cs=w9; i<2; ++i) (*rr++) -= (*cs++);
  /* #163: @12 = @4[0] */
  for (rr=(&w12), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #164: (@0[36] = @12) */
  for (rr=w0+36, ss=(&w12); rr!=w0+37; rr+=1) *rr = *ss++;
  /* #165: @12 = @4[1] */
  for (rr=(&w12), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #166: (@0[37] = @12) */
  for (rr=w0+37, ss=(&w12); rr!=w0+38; rr+=1) *rr = *ss++;
  /* #167: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #168: (@0[38] = @12) */
  for (rr=w0+38, ss=(&w12); rr!=w0+39; rr+=1) *rr = *ss++;
  /* #169: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #170: (@0[39] = @12) */
  for (rr=w0+39, ss=(&w12); rr!=w0+40; rr+=1) *rr = *ss++;
  /* #171: @2 = input[0][21] */
  casadi_copy(arg[0] ? arg[0]+72 : 0, 5, w2);
  /* #172: @4 = input[0][22] */
  casadi_copy(arg[0] ? arg[0]+77 : 0, 2, w4);
  /* #173: @3 = (@4-@3) */
  for (i=0, rr=w3, cr=w4, cs=w3; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #174: @5 = @1[7:9] */
  for (rr=w5, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #175: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #176: @7 = 00 */
  /* #177: {@10, @11, NULL, NULL} = adj1_fJDisc(@2, @3, @5, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w3;
  arg1[2]=w5;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w11;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #178: @9 = (@9-@11) */
  for (i=0, rr=w9, cs=w11; i<2; ++i) (*rr++) -= (*cs++);
  /* #179: @12 = @9[0] */
  for (rr=(&w12), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #180: (@0[40] = @12) */
  for (rr=w0+40, ss=(&w12); rr!=w0+41; rr+=1) *rr = *ss++;
  /* #181: @12 = @9[1] */
  for (rr=(&w12), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #182: (@0[41] = @12) */
  for (rr=w0+41, ss=(&w12); rr!=w0+42; rr+=1) *rr = *ss++;
  /* #183: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #184: (@0[42] = @12) */
  for (rr=w0+42, ss=(&w12); rr!=w0+43; rr+=1) *rr = *ss++;
  /* #185: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #186: (@0[43] = @12) */
  for (rr=w0+43, ss=(&w12); rr!=w0+44; rr+=1) *rr = *ss++;
  /* #187: @10 = input[0][23] */
  casadi_copy(arg[0] ? arg[0]+79 : 0, 5, w10);
  /* #188: @9 = input[0][24] */
  casadi_copy(arg[0] ? arg[0]+84 : 0, 2, w9);
  /* #189: @4 = (@9-@4) */
  for (i=0, rr=w4, cr=w9, cs=w4; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #190: @3 = @1[7:9] */
  for (rr=w3, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #191: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #192: @7 = 00 */
  /* #193: {@2, @5, NULL, NULL} = adj1_fJDisc(@10, @4, @3, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w4;
  arg1[2]=w3;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w5;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #194: @11 = (@11-@5) */
  for (i=0, rr=w11, cs=w5; i<2; ++i) (*rr++) -= (*cs++);
  /* #195: @12 = @11[0] */
  for (rr=(&w12), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #196: (@0[44] = @12) */
  for (rr=w0+44, ss=(&w12); rr!=w0+45; rr+=1) *rr = *ss++;
  /* #197: @12 = @11[1] */
  for (rr=(&w12), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #198: (@0[45] = @12) */
  for (rr=w0+45, ss=(&w12); rr!=w0+46; rr+=1) *rr = *ss++;
  /* #199: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #200: (@0[46] = @12) */
  for (rr=w0+46, ss=(&w12); rr!=w0+47; rr+=1) *rr = *ss++;
  /* #201: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #202: (@0[47] = @12) */
  for (rr=w0+47, ss=(&w12); rr!=w0+48; rr+=1) *rr = *ss++;
  /* #203: @2 = input[0][25] */
  casadi_copy(arg[0] ? arg[0]+86 : 0, 5, w2);
  /* #204: @11 = input[0][26] */
  casadi_copy(arg[0] ? arg[0]+91 : 0, 2, w11);
  /* #205: @9 = (@11-@9) */
  for (i=0, rr=w9, cr=w11, cs=w9; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #206: @4 = @1[7:9] */
  for (rr=w4, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #207: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #208: @7 = 00 */
  /* #209: {@10, @3, NULL, NULL} = adj1_fJDisc(@2, @9, @4, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w9;
  arg1[2]=w4;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w3;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #210: @5 = (@5-@3) */
  for (i=0, rr=w5, cs=w3; i<2; ++i) (*rr++) -= (*cs++);
  /* #211: @12 = @5[0] */
  for (rr=(&w12), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #212: (@0[48] = @12) */
  for (rr=w0+48, ss=(&w12); rr!=w0+49; rr+=1) *rr = *ss++;
  /* #213: @12 = @5[1] */
  for (rr=(&w12), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #214: (@0[49] = @12) */
  for (rr=w0+49, ss=(&w12); rr!=w0+50; rr+=1) *rr = *ss++;
  /* #215: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #216: (@0[50] = @12) */
  for (rr=w0+50, ss=(&w12); rr!=w0+51; rr+=1) *rr = *ss++;
  /* #217: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #218: (@0[51] = @12) */
  for (rr=w0+51, ss=(&w12); rr!=w0+52; rr+=1) *rr = *ss++;
  /* #219: @10 = input[0][27] */
  casadi_copy(arg[0] ? arg[0]+93 : 0, 5, w10);
  /* #220: @5 = input[0][28] */
  casadi_copy(arg[0] ? arg[0]+98 : 0, 2, w5);
  /* #221: @11 = (@5-@11) */
  for (i=0, rr=w11, cr=w5, cs=w11; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #222: @9 = @1[7:9] */
  for (rr=w9, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #223: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #224: @7 = 00 */
  /* #225: {@2, @4, NULL, NULL} = adj1_fJDisc(@10, @11, @9, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w11;
  arg1[2]=w9;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w4;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #226: @3 = (@3-@4) */
  for (i=0, rr=w3, cs=w4; i<2; ++i) (*rr++) -= (*cs++);
  /* #227: @12 = @3[0] */
  for (rr=(&w12), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #228: (@0[52] = @12) */
  for (rr=w0+52, ss=(&w12); rr!=w0+53; rr+=1) *rr = *ss++;
  /* #229: @12 = @3[1] */
  for (rr=(&w12), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #230: (@0[53] = @12) */
  for (rr=w0+53, ss=(&w12); rr!=w0+54; rr+=1) *rr = *ss++;
  /* #231: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #232: (@0[54] = @12) */
  for (rr=w0+54, ss=(&w12); rr!=w0+55; rr+=1) *rr = *ss++;
  /* #233: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #234: (@0[55] = @12) */
  for (rr=w0+55, ss=(&w12); rr!=w0+56; rr+=1) *rr = *ss++;
  /* #235: @2 = input[0][29] */
  casadi_copy(arg[0] ? arg[0]+100 : 0, 5, w2);
  /* #236: @3 = input[0][30] */
  casadi_copy(arg[0] ? arg[0]+105 : 0, 2, w3);
  /* #237: @5 = (@3-@5) */
  for (i=0, rr=w5, cr=w3, cs=w5; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #238: @11 = @1[7:9] */
  for (rr=w11, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #239: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #240: @7 = 00 */
  /* #241: {@10, @9, NULL, NULL} = adj1_fJDisc(@2, @5, @11, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w5;
  arg1[2]=w11;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w9;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #242: @4 = (@4-@9) */
  for (i=0, rr=w4, cs=w9; i<2; ++i) (*rr++) -= (*cs++);
  /* #243: @12 = @4[0] */
  for (rr=(&w12), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #244: (@0[56] = @12) */
  for (rr=w0+56, ss=(&w12); rr!=w0+57; rr+=1) *rr = *ss++;
  /* #245: @12 = @4[1] */
  for (rr=(&w12), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #246: (@0[57] = @12) */
  for (rr=w0+57, ss=(&w12); rr!=w0+58; rr+=1) *rr = *ss++;
  /* #247: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #248: (@0[58] = @12) */
  for (rr=w0+58, ss=(&w12); rr!=w0+59; rr+=1) *rr = *ss++;
  /* #249: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #250: (@0[59] = @12) */
  for (rr=w0+59, ss=(&w12); rr!=w0+60; rr+=1) *rr = *ss++;
  /* #251: @10 = input[0][31] */
  casadi_copy(arg[0] ? arg[0]+107 : 0, 5, w10);
  /* #252: @4 = input[0][32] */
  casadi_copy(arg[0] ? arg[0]+112 : 0, 2, w4);
  /* #253: @3 = (@4-@3) */
  for (i=0, rr=w3, cr=w4, cs=w3; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #254: @5 = @1[7:9] */
  for (rr=w5, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #255: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #256: @7 = 00 */
  /* #257: {@2, @11, NULL, NULL} = adj1_fJDisc(@10, @3, @5, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w3;
  arg1[2]=w5;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w11;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #258: @9 = (@9-@11) */
  for (i=0, rr=w9, cs=w11; i<2; ++i) (*rr++) -= (*cs++);
  /* #259: @12 = @9[0] */
  for (rr=(&w12), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #260: (@0[60] = @12) */
  for (rr=w0+60, ss=(&w12); rr!=w0+61; rr+=1) *rr = *ss++;
  /* #261: @12 = @9[1] */
  for (rr=(&w12), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #262: (@0[61] = @12) */
  for (rr=w0+61, ss=(&w12); rr!=w0+62; rr+=1) *rr = *ss++;
  /* #263: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #264: (@0[62] = @12) */
  for (rr=w0+62, ss=(&w12); rr!=w0+63; rr+=1) *rr = *ss++;
  /* #265: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #266: (@0[63] = @12) */
  for (rr=w0+63, ss=(&w12); rr!=w0+64; rr+=1) *rr = *ss++;
  /* #267: @2 = input[0][33] */
  casadi_copy(arg[0] ? arg[0]+114 : 0, 5, w2);
  /* #268: @9 = input[0][34] */
  casadi_copy(arg[0] ? arg[0]+119 : 0, 2, w9);
  /* #269: @4 = (@9-@4) */
  for (i=0, rr=w4, cr=w9, cs=w4; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #270: @3 = @1[7:9] */
  for (rr=w3, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #271: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #272: @7 = 00 */
  /* #273: {@10, @5, NULL, NULL} = adj1_fJDisc(@2, @4, @3, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w4;
  arg1[2]=w3;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w5;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #274: @11 = (@11-@5) */
  for (i=0, rr=w11, cs=w5; i<2; ++i) (*rr++) -= (*cs++);
  /* #275: @12 = @11[0] */
  for (rr=(&w12), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #276: (@0[64] = @12) */
  for (rr=w0+64, ss=(&w12); rr!=w0+65; rr+=1) *rr = *ss++;
  /* #277: @12 = @11[1] */
  for (rr=(&w12), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #278: (@0[65] = @12) */
  for (rr=w0+65, ss=(&w12); rr!=w0+66; rr+=1) *rr = *ss++;
  /* #279: @12 = @10[1] */
  for (rr=(&w12), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #280: (@0[66] = @12) */
  for (rr=w0+66, ss=(&w12); rr!=w0+67; rr+=1) *rr = *ss++;
  /* #281: @12 = @10[3] */
  for (rr=(&w12), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #282: (@0[67] = @12) */
  for (rr=w0+67, ss=(&w12); rr!=w0+68; rr+=1) *rr = *ss++;
  /* #283: @10 = input[0][35] */
  casadi_copy(arg[0] ? arg[0]+121 : 0, 5, w10);
  /* #284: @11 = input[0][36] */
  casadi_copy(arg[0] ? arg[0]+126 : 0, 2, w11);
  /* #285: @9 = (@11-@9) */
  for (i=0, rr=w9, cr=w11, cs=w9; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #286: @4 = @1[7:9] */
  for (rr=w4, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #287: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #288: @7 = 00 */
  /* #289: {@2, @3, NULL, NULL} = adj1_fJDisc(@10, @9, @4, @6, @7, @8) */
  arg1[0]=w10;
  arg1[1]=w9;
  arg1[2]=w4;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w2;
  res1[1]=w3;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #290: @5 = (@5-@3) */
  for (i=0, rr=w5, cs=w3; i<2; ++i) (*rr++) -= (*cs++);
  /* #291: @12 = @5[0] */
  for (rr=(&w12), ss=w5+0; ss!=w5+1; ss+=1) *rr++ = *ss;
  /* #292: (@0[68] = @12) */
  for (rr=w0+68, ss=(&w12); rr!=w0+69; rr+=1) *rr = *ss++;
  /* #293: @12 = @5[1] */
  for (rr=(&w12), ss=w5+1; ss!=w5+2; ss+=1) *rr++ = *ss;
  /* #294: (@0[69] = @12) */
  for (rr=w0+69, ss=(&w12); rr!=w0+70; rr+=1) *rr = *ss++;
  /* #295: @12 = @2[1] */
  for (rr=(&w12), ss=w2+1; ss!=w2+2; ss+=1) *rr++ = *ss;
  /* #296: (@0[70] = @12) */
  for (rr=w0+70, ss=(&w12); rr!=w0+71; rr+=1) *rr = *ss++;
  /* #297: @12 = @2[3] */
  for (rr=(&w12), ss=w2+3; ss!=w2+4; ss+=1) *rr++ = *ss;
  /* #298: (@0[71] = @12) */
  for (rr=w0+71, ss=(&w12); rr!=w0+72; rr+=1) *rr = *ss++;
  /* #299: @2 = input[0][37] */
  casadi_copy(arg[0] ? arg[0]+128 : 0, 5, w2);
  /* #300: @5 = input[0][38] */
  casadi_copy(arg[0] ? arg[0]+133 : 0, 2, w5);
  /* #301: @5 = (@5-@11) */
  for (i=0, rr=w5, cs=w11; i<2; ++i) (*rr++) -= (*cs++);
  /* #302: @11 = @1[7:9] */
  for (rr=w11, ss=w1+7; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #303: @6 = @1[9:13] */
  for (rr=w6, ss=w1+9; ss!=w1+13; ss+=1) *rr++ = *ss;
  /* #304: @7 = 00 */
  /* #305: {@10, @9, NULL, NULL} = adj1_fJDisc(@2, @5, @11, @6, @7, @8) */
  arg1[0]=w2;
  arg1[1]=w5;
  arg1[2]=w11;
  arg1[3]=w6;
  arg1[4]=0;
  arg1[5]=(&w8);
  res1[0]=w10;
  res1[1]=w9;
  res1[2]=0;
  res1[3]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #306: @3 = (@3-@9) */
  for (i=0, rr=w3, cs=w9; i<2; ++i) (*rr++) -= (*cs++);
  /* #307: @8 = @3[0] */
  for (rr=(&w8), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #308: (@0[72] = @8) */
  for (rr=w0+72, ss=(&w8); rr!=w0+73; rr+=1) *rr = *ss++;
  /* #309: @8 = @3[1] */
  for (rr=(&w8), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #310: (@0[73] = @8) */
  for (rr=w0+73, ss=(&w8); rr!=w0+74; rr+=1) *rr = *ss++;
  /* #311: @8 = @10[1] */
  for (rr=(&w8), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #312: (@0[74] = @8) */
  for (rr=w0+74, ss=(&w8); rr!=w0+75; rr+=1) *rr = *ss++;
  /* #313: @8 = @10[3] */
  for (rr=(&w8), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #314: (@0[75] = @8) */
  for (rr=w0+75, ss=(&w8); rr!=w0+76; rr+=1) *rr = *ss++;
  /* #315: @8 = @9[0] */
  for (rr=(&w8), ss=w9+0; ss!=w9+1; ss+=1) *rr++ = *ss;
  /* #316: (@0[76] = @8) */
  for (rr=w0+76, ss=(&w8); rr!=w0+77; rr+=1) *rr = *ss++;
  /* #317: @8 = @9[1] */
  for (rr=(&w8), ss=w9+1; ss!=w9+2; ss+=1) *rr++ = *ss;
  /* #318: (@0[77] = @8) */
  for (rr=w0+77, ss=(&w8); rr!=w0+78; rr+=1) *rr = *ss++;
  /* #319: output[0][0] = @0 */
  casadi_copy(w0, 78, res[0]);
  return 0;
}

int qp_gradJ(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

void qp_gradJ_incref(void) {
}

void qp_gradJ_decref(void) {
}

int qp_gradJ_n_in(void) { return 2;}

int qp_gradJ_n_out(void) { return 1;}

const char* qp_gradJ_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* qp_gradJ_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const int* qp_gradJ_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const int* qp_gradJ_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int qp_gradJ_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 140;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
