/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) qp_h_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Printing routine */
#define PRINTF printf

static const int casadi_s0[144] = {140, 1, 0, 140, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139};
static const int casadi_s1[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const int casadi_s2[104] = {100, 1, 0, 100, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99};

void casadi_copy(const casadi_real* x, int n, casadi_real* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

/* fxdot:(i0[5],i1[2])->(o0[5]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3, w4, w5, *w6=w+6, w7, *w8=w+9, w9, w10, w11, w12, w13;
  /* #0: @0 = 0.5 */
  w0 = 5.0000000000000000e-001;
  /* #1: @1 = 700 */
  w1 = 700.;
  /* #2: @2 = 1005 */
  w2 = 1005.;
  /* #3: @3 = 0.647137 */
  w3 = 6.4713654995349645e-001;
  /* #4: @4 = -0.1561 */
  w4 = -1.5609999999999999e-001;
  /* #5: @5 = 0.2414 */
  w5 = 2.4140000000000000e-001;
  /* #6: @6 = input[1][0] */
  casadi_copy(arg[1], 2, w6);
  /* #7: @7 = @6[0] */
  for (rr=(&w7), ss=w6+0; ss!=w6+1; ss+=1) *rr++ = *ss;
  /* #8: @5 = (@5*@7) */
  w5 *= w7;
  /* #9: @4 = (@4+@5) */
  w4 += w5;
  /* #10: @5 = 0.2819 */
  w5 = 2.8189999999999998e-001;
  /* #11: @8 = input[0][0] */
  casadi_copy(arg[0], 5, w8);
  /* #12: @9 = @8[2] */
  for (rr=(&w9), ss=w8+2; ss!=w8+3; ss+=1) *rr++ = *ss;
  /* #13: @10 = 100000 */
  w10 = 100000.;
  /* #14: @10 = (@9/@10) */
  w10  = (w9/w10);
  /* #15: @5 = (@5*@10) */
  w5 *= w10;
  /* #16: @4 = (@4+@5) */
  w4 += w5;
  /* #17: @5 = -0.2455 */
  w5 = -2.4550000000000000e-001;
  /* #18: @11 = sq(@7) */
  w11 = sq( w7 );
  /* #19: @5 = (@5*@11) */
  w5 *= w11;
  /* #20: @4 = (@4+@5) */
  w4 += w5;
  /* #21: @5 = -0.2829 */
  w5 = -2.8289999999999998e-001;
  /* #22: @5 = (@5*@7) */
  w5 *= w7;
  /* #23: @5 = (@5*@10) */
  w5 *= w10;
  /* #24: @4 = (@4+@5) */
  w4 += w5;
  /* #25: @5 = -0.1244 */
  w5 = -1.2440000000000000e-001;
  /* #26: @11 = sq(@10) */
  w11 = sq( w10 );
  /* #27: @5 = (@5*@11) */
  w5 *= w11;
  /* #28: @4 = (@4+@5) */
  w4 += w5;
  /* #29: @5 = 0.1076 */
  w5 = 1.0760000000000000e-001;
  /* #30: @11 = 3 */
  w11 = 3.;
  /* #31: @11 = pow(@7,@11) */
  w11  = pow(w7,w11);
  /* #32: @5 = (@5*@11) */
  w5 *= w11;
  /* #33: @4 = (@4+@5) */
  w4 += w5;
  /* #34: @5 = 0.199 */
  w5 = 1.9900000000000001e-001;
  /* #35: @11 = sq(@7) */
  w11 = sq( w7 );
  /* #36: @5 = (@5*@11) */
  w5 *= w11;
  /* #37: @5 = (@5*@10) */
  w5 *= w10;
  /* #38: @4 = (@4+@5) */
  w4 += w5;
  /* #39: @5 = 0.05707 */
  w5 = 5.7070000000000003e-002;
  /* #40: @5 = (@5*@7) */
  w5 *= w7;
  /* #41: @11 = sq(@10) */
  w11 = sq( w10 );
  /* #42: @5 = (@5*@11) */
  w5 *= w11;
  /* #43: @4 = (@4+@5) */
  w4 += w5;
  /* #44: @5 = 0.02601 */
  w5 = 2.6009999999999998e-002;
  /* #45: @11 = 3 */
  w11 = 3.;
  /* #46: @11 = pow(@10,@11) */
  w11  = pow(w10,w11);
  /* #47: @5 = (@5*@11) */
  w5 *= w11;
  /* #48: @4 = (@4+@5) */
  w4 += w5;
  /* #49: @5 = -0.08487 */
  w5 = -8.4870000000000001e-002;
  /* #50: @11 = 3 */
  w11 = 3.;
  /* #51: @11 = pow(@7,@11) */
  w11  = pow(w7,w11);
  /* #52: @5 = (@5*@11) */
  w5 *= w11;
  /* #53: @5 = (@5*@10) */
  w5 *= w10;
  /* #54: @4 = (@4+@5) */
  w4 += w5;
  /* #55: @5 = -0.000165 */
  w5 = -1.6500000000000000e-004;
  /* #56: @11 = sq(@7) */
  w11 = sq( w7 );
  /* #57: @5 = (@5*@11) */
  w5 *= w11;
  /* #58: @11 = sq(@10) */
  w11 = sq( w10 );
  /* #59: @5 = (@5*@11) */
  w5 *= w11;
  /* #60: @4 = (@4+@5) */
  w4 += w5;
  /* #61: @5 = -0.007593 */
  w5 = -7.5929999999999999e-003;
  /* #62: @5 = (@5*@7) */
  w5 *= w7;
  /* #63: @7 = 3 */
  w7 = 3.;
  /* #64: @7 = pow(@10,@7) */
  w7  = pow(w10,w7);
  /* #65: @5 = (@5*@7) */
  w5 *= w7;
  /* #66: @4 = (@4+@5) */
  w4 += w5;
  /* #67: @5 = -0.001824 */
  w5 = -1.8240000000000001e-003;
  /* #68: @7 = 4 */
  w7 = 4.;
  /* #69: @7 = pow(@10,@7) */
  w7  = pow(w10,w7);
  /* #70: @5 = (@5*@7) */
  w5 *= w7;
  /* #71: @4 = (@4+@5) */
  w4 += w5;
  /* #72: @4 = (@4*@10) */
  w4 *= w10;
  /* #73: @3 = (@3*@4) */
  w3 *= w4;
  /* #74: @2 = (@2*@3) */
  w2 *= w3;
  /* #75: @1 = (@1*@2) */
  w1 *= w2;
  /* #76: @0 = (@0*@1) */
  w0 *= w1;
  /* #77: @1 = 1 */
  w1 = 1.;
  /* #78: @2 = -0.285714 */
  w2 = -2.8571428571428564e-001;
  /* #79: @10 = pow(@10,@2) */
  w10  = pow(w10,w2);
  /* #80: @1 = (@1-@10) */
  w1 -= w10;
  /* #81: @0 = (@0*@1) */
  w0 *= w1;
  /* #82: @1 = 293.15 */
  w1 = 2.9314999999999998e+002;
  /* #83: @10 = 1005 */
  w10 = 1005.;
  /* #84: @2 = 0.1686 */
  w2 = 1.6860000000000000e-001;
  /* #85: @4 = -0.2142 */
  w4 = -2.1420000000000000e-001;
  /* #86: @5 = @8[1] */
  for (rr=(&w5), ss=w8+1; ss!=w8+2; ss+=1) *rr++ = *ss;
  /* #87: @7 = 100000 */
  w7 = 100000.;
  /* #88: @7 = (@5/@7) */
  w7  = (w5/w7);
  /* #89: @4 = (@4*@7) */
  w4 *= w7;
  /* #90: @2 = (@2+@4) */
  w2 += w4;
  /* #91: @4 = 8.4215e-006 */
  w4 = 8.4215000000000006e-006;
  /* #92: @11 = @8[0] */
  for (rr=(&w11), ss=w8+0; ss!=w8+1; ss+=1) *rr++ = *ss;
  /* #93: @4 = (@4*@11) */
  w4 *= w11;
  /* #94: @2 = (@2+@4) */
  w2 += w4;
  /* #95: @4 = -0.02582 */
  w4 = -2.5819999999999999e-002;
  /* #96: @12 = sq(@7) */
  w12 = sq( w7 );
  /* #97: @4 = (@4*@12) */
  w4 *= w12;
  /* #98: @2 = (@2+@4) */
  w2 += w4;
  /* #99: @4 = 1.2347e-005 */
  w4 = 1.2347000000000001e-005;
  /* #100: @4 = (@4*@7) */
  w4 *= w7;
  /* #101: @4 = (@4*@11) */
  w4 *= w11;
  /* #102: @2 = (@2+@4) */
  w2 += w4;
  /* #103: @4 = -3.7187e-010 */
  w4 = -3.7186999999999998e-010;
  /* #104: @12 = sq(@11) */
  w12 = sq( w11 );
  /* #105: @4 = (@4*@12) */
  w4 *= w12;
  /* #106: @2 = (@2+@4) */
  w2 += w4;
  /* #107: @10 = (@10*@2) */
  w10 *= w2;
  /* #108: @1 = (@1*@10) */
  w1 *= w10;
  /* #109: @10 = 0.48 */
  w10 = 4.7999999999999998e-001;
  /* #110: @1 = (@1/@10) */
  w1 /= w10;
  /* #111: @10 = 0.285714 */
  w10 = 2.8571428571428564e-001;
  /* #112: @7 = pow(@7,@10) */
  w7  = pow(w7,w10);
  /* #113: @10 = 1 */
  w10 = 1.;
  /* #114: @7 = (@7-@10) */
  w7 -= w10;
  /* #115: @1 = (@1*@7) */
  w1 *= w7;
  /* #116: @0 = (@0-@1) */
  w0 -= w1;
  /* #117: @1 = 155 */
  w1 = 155.;
  /* #118: @0 = (@0-@1) */
  w0 -= w1;
  /* #119: @1 = 1.8238e-005 */
  w1 = 1.8238000000000001e-005;
  /* #120: @1 = (@1*@11) */
  w1 *= w11;
  /* #121: @0 = (@0/@1) */
  w0 /= w1;
  /* #122: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #123: @0 = 2.77742e+007 */
  w0 = 2.7774193548387095e+007;
  /* #124: @1 = 0.01494 */
  w1 = 1.4940000000000000e-002;
  /* #125: @11 = 1 */
  w11 = 1.;
  /* #126: @7 = -30.4231 */
  w7 = -3.0423100000000002e+001;
  /* #127: @10 = 0.6858 */
  w10 = 6.8579999999999997e-001;
  /* #128: @4 = @6[1] */
  for (rr=(&w4), ss=w6+1; ss!=w6+2; ss+=1) *rr++ = *ss;
  /* #129: @10 = (@10+@4) */
  w10 += w4;
  /* #130: @12 = 1.5797 */
  w12 = 1.5797000000000001e+000;
  /* #131: @10 = (@10/@12) */
  w10 /= w12;
  /* #132: @12 = 10 */
  w12 = 10.;
  /* #133: @10 = pow(@10,@12) */
  w10  = pow(w10,w12);
  /* #134: @7 = (@7*@10) */
  w7 *= w10;
  /* #135: @7 = exp(@7) */
  w7 = exp( w7 );
  /* #136: @11 = (@11-@7) */
  w11 -= w7;
  /* #137: @1 = (@1*@11) */
  w1 *= w11;
  /* #138: @11 = 0.5163 */
  w11 = 5.1629999999999998e-001;
  /* #139: @7 = 14500 */
  w7 = 14500.;
  /* #140: @10 = -8.658 */
  w10 = -8.6579999999999995e+000;
  /* #141: @12 = (@9/@5) */
  w12  = (w9/w5);
  /* #142: @10 = (@10*@12) */
  w10 *= w12;
  /* #143: @10 = exp(@10) */
  w10 = exp( w10 );
  /* #144: @7 = (@7*@10) */
  w7 *= w10;
  /* #145: @11 = (@11+@7) */
  w11 += w7;
  /* #146: @1 = (@1/@11) */
  w1 /= w11;
  /* #147: @11 = 0.5 */
  w11 = 5.0000000000000000e-001;
  /* #148: @7 = 1e-008 */
  w7 = 1.0000000000000000e-008;
  /* #149: @10 = 0.002 */
  w10 = 2.0000000000000000e-003;
  /* #150: @13 = 0.72 */
  w13 = 7.1999999999999997e-001;
  /* #151: @4 = (@4-@13) */
  w4 -= w13;
  /* #152: @10 = (@10*@4) */
  w10 *= w4;
  /* #153: @4 = sq(@10) */
  w4 = sq( w10 );
  /* #154: @7 = (@7+@4) */
  w7 += w4;
  /* #155: @7 = sqrt(@7) */
  w7 = sqrt( w7 );
  /* #156: @11 = (@11*@7) */
  w11 *= w7;
  /* #157: @7 = 0.5 */
  w7 = 5.0000000000000000e-001;
  /* #158: @7 = (@7*@10) */
  w7 *= w10;
  /* #159: @11 = (@11+@7) */
  w11 += w7;
  /* #160: @1 = (@1+@11) */
  w1 += w11;
  /* #161: @11 = (@2+@1) */
  w11  = (w2+w1);
  /* #162: @7 = 0.005145 */
  w7 = 5.1450000000000003e-003;
  /* #163: @10 = 0.011 */
  w10 = 1.0999999999999999e-002;
  /* #164: @4 = 86100 */
  w4 = 86100.;
  /* #165: @4 = (@5/@4) */
  w4  = (w5/w4);
  /* #166: @10 = (@10*@4) */
  w10 *= w4;
  /* #167: @7 = (@7+@10) */
  w7 += w10;
  /* #168: @10 = 0.01099 */
  w10 = 1.0990000000000000e-002;
  /* #169: @10 = (@10*@12) */
  w10 *= w12;
  /* #170: @7 = (@7+@10) */
  w7 += w10;
  /* #171: @11 = (@11-@7) */
  w11 -= w7;
  /* #172: @0 = (@0*@11) */
  w0 *= w11;
  /* #173: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #174: @0 = 1.33933e+007 */
  w0 = 1.3393333333333334e+007;
  /* #175: @11 = 0.00073521 */
  w11 = 7.3521000000000003e-004;
  /* #176: @11 = (@11+@7) */
  w11 += w7;
  /* #177: @10 = (@11-@1) */
  w10  = (w11-w1);
  /* #178: @10 = (@10-@3) */
  w10 -= w3;
  /* #179: @0 = (@0*@10) */
  w0 *= w10;
  /* #180: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #181: @0 = 86100 */
  w0 = 86100.;
  /* #182: @10 = 0.0031 */
  w10 = 3.1000000000000003e-003;
  /* #183: @10 = (@10*@5) */
  w10 *= w5;
  /* #184: @0 = (@0/@10) */
  w0 /= w10;
  /* #185: @10 = 0.23142 */
  w10 = 2.3141999999999999e-001;
  /* #186: @5 = @8[3] */
  for (rr=(&w5), ss=w8+3; ss!=w8+4; ss+=1) *rr++ = *ss;
  /* #187: @10 = (@10-@5) */
  w10 -= w5;
  /* #188: @10 = (@10*@2) */
  w10 *= w2;
  /* #189: @2 = @8[4] */
  for (rr=(&w2), ss=w8+4; ss!=w8+5; ss+=1) *rr++ = *ss;
  /* #190: @3 = (@2-@5) */
  w3  = (w2-w5);
  /* #191: @3 = (@3*@1) */
  w3 *= w1;
  /* #192: @10 = (@10+@3) */
  w10 += w3;
  /* #193: @0 = (@0*@10) */
  w0 *= w10;
  /* #194: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #195: @0 = 200900 */
  w0 = 200900.;
  /* #196: @10 = 0.0008 */
  w10 = 8.0000000000000004e-004;
  /* #197: @10 = (@10*@9) */
  w10 *= w9;
  /* #198: @0 = (@0/@10) */
  w0 /= w10;
  /* #199: @7 = (@7*@5) */
  w7 *= w5;
  /* #200: @5 = 0.00249971 */
  w5 = 2.4997140000000001e-003;
  /* #201: @7 = (@7-@5) */
  w7 -= w5;
  /* #202: @7 = (@7/@11) */
  w7 /= w11;
  /* #203: @7 = (@7-@2) */
  w7 -= w2;
  /* #204: @7 = (@7*@11) */
  w7 *= w11;
  /* #205: @0 = (@0*@7) */
  w0 *= w7;
  /* #206: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  return 0;
}

/* fxDisc:(i0[5],i1[2])->(o0[5]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real **res1=res+1, *rr;
  const casadi_real **arg1=arg+2, *cr, *cs;
  int i;
  casadi_real *w0=w+19, w1, *w2=w+25, *w3=w+27, w4, *w5=w+33, *w6=w+38;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w0);
  /* #1: @1 = 0.00333333 */
  w1 = 3.3333333333333335e-003;
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 2, w2);
  /* #3: @3 = fxdot(@0, @2) */
  arg1[0]=w0;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #5: @5 = (@4*@3) */
  for (i=0, rr=w5, cs=w3; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #6: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #7: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = (2.*@6) */
  for (i=0, rr=w5, cs=w6; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #9: @3 = (@3+@5) */
  for (i=0, rr=w3, cs=w5; i<5; ++i) (*rr++) += (*cs++);
  /* #10: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #11: @6 = (@4*@6) */
  for (i=0, rr=w6, cs=w6; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #12: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #13: @5 = fxdot(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: @6 = (2.*@5) */
  for (i=0, rr=w6, cs=w5; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #15: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #16: @4 = 0.02 */
  w4 = 2.0000000000000000e-002;
  /* #17: @5 = (@4*@5) */
  for (i=0, rr=w5, cs=w5; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #18: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #19: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #21: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<5; ++i) (*rr++)  = (w1*(*cs++));
  /* #22: @0 = (@0+@3) */
  for (i=0, rr=w0, cs=w3; i<5; ++i) (*rr++) += (*cs++);
  /* #23: @1 = 0.00333333 */
  w1 = 3.3333333333333335e-003;
  /* #24: @3 = fxdot(@0, @2) */
  arg1[0]=w0;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #26: @6 = (@4*@3) */
  for (i=0, rr=w6, cs=w3; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #27: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #28: @5 = fxdot(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #29: @6 = (2.*@5) */
  for (i=0, rr=w6, cs=w5; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #30: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #31: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #32: @5 = (@4*@5) */
  for (i=0, rr=w5, cs=w5; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #33: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #34: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #35: @5 = (2.*@6) */
  for (i=0, rr=w5, cs=w6; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #36: @3 = (@3+@5) */
  for (i=0, rr=w3, cs=w5; i<5; ++i) (*rr++) += (*cs++);
  /* #37: @4 = 0.02 */
  w4 = 2.0000000000000000e-002;
  /* #38: @6 = (@4*@6) */
  for (i=0, rr=w6, cs=w6; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #39: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #40: @5 = fxdot(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #41: @3 = (@3+@5) */
  for (i=0, rr=w3, cs=w5; i<5; ++i) (*rr++) += (*cs++);
  /* #42: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<5; ++i) (*rr++)  = (w1*(*cs++));
  /* #43: @0 = (@0+@3) */
  for (i=0, rr=w0, cs=w3; i<5; ++i) (*rr++) += (*cs++);
  /* #44: @1 = 0.00333333 */
  w1 = 3.3333333333333335e-003;
  /* #45: @3 = fxdot(@0, @2) */
  arg1[0]=w0;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #46: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #47: @5 = (@4*@3) */
  for (i=0, rr=w5, cs=w3; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #48: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #49: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #50: @5 = (2.*@6) */
  for (i=0, rr=w5, cs=w6; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #51: @3 = (@3+@5) */
  for (i=0, rr=w3, cs=w5; i<5; ++i) (*rr++) += (*cs++);
  /* #52: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #53: @6 = (@4*@6) */
  for (i=0, rr=w6, cs=w6; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #54: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #55: @5 = fxdot(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #56: @6 = (2.*@5) */
  for (i=0, rr=w6, cs=w5; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #57: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #58: @4 = 0.02 */
  w4 = 2.0000000000000000e-002;
  /* #59: @5 = (@4*@5) */
  for (i=0, rr=w5, cs=w5; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #60: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #61: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #62: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #63: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<5; ++i) (*rr++)  = (w1*(*cs++));
  /* #64: @0 = (@0+@3) */
  for (i=0, rr=w0, cs=w3; i<5; ++i) (*rr++) += (*cs++);
  /* #65: @1 = 0.00333333 */
  w1 = 3.3333333333333335e-003;
  /* #66: @3 = fxdot(@0, @2) */
  arg1[0]=w0;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #67: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #68: @6 = (@4*@3) */
  for (i=0, rr=w6, cs=w3; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #69: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #70: @5 = fxdot(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #71: @6 = (2.*@5) */
  for (i=0, rr=w6, cs=w5; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #72: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #73: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #74: @5 = (@4*@5) */
  for (i=0, rr=w5, cs=w5; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #75: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #76: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #77: @5 = (2.*@6) */
  for (i=0, rr=w5, cs=w6; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #78: @3 = (@3+@5) */
  for (i=0, rr=w3, cs=w5; i<5; ++i) (*rr++) += (*cs++);
  /* #79: @4 = 0.02 */
  w4 = 2.0000000000000000e-002;
  /* #80: @6 = (@4*@6) */
  for (i=0, rr=w6, cs=w6; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #81: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #82: @5 = fxdot(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #83: @3 = (@3+@5) */
  for (i=0, rr=w3, cs=w5; i<5; ++i) (*rr++) += (*cs++);
  /* #84: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<5; ++i) (*rr++)  = (w1*(*cs++));
  /* #85: @0 = (@0+@3) */
  for (i=0, rr=w0, cs=w3; i<5; ++i) (*rr++) += (*cs++);
  /* #86: @1 = 0.00333333 */
  w1 = 3.3333333333333335e-003;
  /* #87: @3 = fxdot(@0, @2) */
  arg1[0]=w0;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #88: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #89: @5 = (@4*@3) */
  for (i=0, rr=w5, cs=w3; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #90: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #91: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #92: @5 = (2.*@6) */
  for (i=0, rr=w5, cs=w6; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #93: @3 = (@3+@5) */
  for (i=0, rr=w3, cs=w5; i<5; ++i) (*rr++) += (*cs++);
  /* #94: @4 = 0.01 */
  w4 = 1.0000000000000000e-002;
  /* #95: @6 = (@4*@6) */
  for (i=0, rr=w6, cs=w6; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #96: @6 = (@0+@6) */
  for (i=0, rr=w6, cr=w0, cs=w6; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #97: @5 = fxdot(@6, @2) */
  arg1[0]=w6;
  arg1[1]=w2;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #98: @6 = (2.*@5) */
  for (i=0, rr=w6, cs=w5; i<5; ++i) *rr++ = (2.* *cs++ );
  /* #99: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #100: @4 = 0.02 */
  w4 = 2.0000000000000000e-002;
  /* #101: @5 = (@4*@5) */
  for (i=0, rr=w5, cs=w5; i<5; ++i) (*rr++)  = (w4*(*cs++));
  /* #102: @5 = (@0+@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<5; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #103: @6 = fxdot(@5, @2) */
  arg1[0]=w5;
  arg1[1]=w2;
  res1[0]=w6;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #104: @3 = (@3+@6) */
  for (i=0, rr=w3, cs=w6; i<5; ++i) (*rr++) += (*cs++);
  /* #105: @3 = (@1*@3) */
  for (i=0, rr=w3, cs=w3; i<5; ++i) (*rr++)  = (w1*(*cs++));
  /* #106: @0 = (@0+@3) */
  for (i=0, rr=w0, cs=w3; i<5; ++i) (*rr++) += (*cs++);
  /* #107: output[0][0] = @0 */
  casadi_copy(w0, 5, res[0]);
  return 0;
}

/* qp_h:(i0[140],i1[13])->(o0[100]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+2, *cs;
  int i;
  casadi_real *w0=w+43, *w1=w+56, *w2=w+61, *w3=w+63;
  /* #0: @0 = input[1][0] */
  casadi_copy(arg[1], 13, w0);
  /* #1: @1 = @0[:5] */
  for (rr=w1, ss=w0+0; ss!=w0+5; ss+=1) *rr++ = *ss;
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 2, w2);
  /* #3: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+2 : 0, 5, w1);
  /* #5: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #6: output[0][0] = @3 */
  casadi_copy(w3, 5, res[0]);
  /* #7: @2 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 2, w2);
  /* #8: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #9: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+9 : 0, 5, w1);
  /* #10: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #11: output[0][1] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+5);
  /* #12: @2 = input[0][4] */
  casadi_copy(arg[0] ? arg[0]+14 : 0, 2, w2);
  /* #13: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: @1 = input[0][5] */
  casadi_copy(arg[0] ? arg[0]+16 : 0, 5, w1);
  /* #15: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #16: output[0][2] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+10);
  /* #17: @2 = input[0][6] */
  casadi_copy(arg[0] ? arg[0]+21 : 0, 2, w2);
  /* #18: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #19: @1 = input[0][7] */
  casadi_copy(arg[0] ? arg[0]+23 : 0, 5, w1);
  /* #20: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #21: output[0][3] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+15);
  /* #22: @2 = input[0][8] */
  casadi_copy(arg[0] ? arg[0]+28 : 0, 2, w2);
  /* #23: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #24: @1 = input[0][9] */
  casadi_copy(arg[0] ? arg[0]+30 : 0, 5, w1);
  /* #25: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #26: output[0][4] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+20);
  /* #27: @2 = input[0][10] */
  casadi_copy(arg[0] ? arg[0]+35 : 0, 2, w2);
  /* #28: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #29: @1 = input[0][11] */
  casadi_copy(arg[0] ? arg[0]+37 : 0, 5, w1);
  /* #30: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #31: output[0][5] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+25);
  /* #32: @2 = input[0][12] */
  casadi_copy(arg[0] ? arg[0]+42 : 0, 2, w2);
  /* #33: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #34: @1 = input[0][13] */
  casadi_copy(arg[0] ? arg[0]+44 : 0, 5, w1);
  /* #35: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #36: output[0][6] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+30);
  /* #37: @2 = input[0][14] */
  casadi_copy(arg[0] ? arg[0]+49 : 0, 2, w2);
  /* #38: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #39: @1 = input[0][15] */
  casadi_copy(arg[0] ? arg[0]+51 : 0, 5, w1);
  /* #40: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #41: output[0][7] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+35);
  /* #42: @2 = input[0][16] */
  casadi_copy(arg[0] ? arg[0]+56 : 0, 2, w2);
  /* #43: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #44: @1 = input[0][17] */
  casadi_copy(arg[0] ? arg[0]+58 : 0, 5, w1);
  /* #45: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #46: output[0][8] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+40);
  /* #47: @2 = input[0][18] */
  casadi_copy(arg[0] ? arg[0]+63 : 0, 2, w2);
  /* #48: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #49: @1 = input[0][19] */
  casadi_copy(arg[0] ? arg[0]+65 : 0, 5, w1);
  /* #50: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #51: output[0][9] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+45);
  /* #52: @2 = input[0][20] */
  casadi_copy(arg[0] ? arg[0]+70 : 0, 2, w2);
  /* #53: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #54: @1 = input[0][21] */
  casadi_copy(arg[0] ? arg[0]+72 : 0, 5, w1);
  /* #55: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #56: output[0][10] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+50);
  /* #57: @2 = input[0][22] */
  casadi_copy(arg[0] ? arg[0]+77 : 0, 2, w2);
  /* #58: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #59: @1 = input[0][23] */
  casadi_copy(arg[0] ? arg[0]+79 : 0, 5, w1);
  /* #60: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #61: output[0][11] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+55);
  /* #62: @2 = input[0][24] */
  casadi_copy(arg[0] ? arg[0]+84 : 0, 2, w2);
  /* #63: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #64: @1 = input[0][25] */
  casadi_copy(arg[0] ? arg[0]+86 : 0, 5, w1);
  /* #65: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #66: output[0][12] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+60);
  /* #67: @2 = input[0][26] */
  casadi_copy(arg[0] ? arg[0]+91 : 0, 2, w2);
  /* #68: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #69: @1 = input[0][27] */
  casadi_copy(arg[0] ? arg[0]+93 : 0, 5, w1);
  /* #70: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #71: output[0][13] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+65);
  /* #72: @2 = input[0][28] */
  casadi_copy(arg[0] ? arg[0]+98 : 0, 2, w2);
  /* #73: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #74: @1 = input[0][29] */
  casadi_copy(arg[0] ? arg[0]+100 : 0, 5, w1);
  /* #75: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #76: output[0][14] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+70);
  /* #77: @2 = input[0][30] */
  casadi_copy(arg[0] ? arg[0]+105 : 0, 2, w2);
  /* #78: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #79: @1 = input[0][31] */
  casadi_copy(arg[0] ? arg[0]+107 : 0, 5, w1);
  /* #80: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #81: output[0][15] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+75);
  /* #82: @2 = input[0][32] */
  casadi_copy(arg[0] ? arg[0]+112 : 0, 2, w2);
  /* #83: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #84: @1 = input[0][33] */
  casadi_copy(arg[0] ? arg[0]+114 : 0, 5, w1);
  /* #85: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #86: output[0][16] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+80);
  /* #87: @2 = input[0][34] */
  casadi_copy(arg[0] ? arg[0]+119 : 0, 2, w2);
  /* #88: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #89: @1 = input[0][35] */
  casadi_copy(arg[0] ? arg[0]+121 : 0, 5, w1);
  /* #90: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #91: output[0][17] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+85);
  /* #92: @2 = input[0][36] */
  casadi_copy(arg[0] ? arg[0]+126 : 0, 2, w2);
  /* #93: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #94: @1 = input[0][37] */
  casadi_copy(arg[0] ? arg[0]+128 : 0, 5, w1);
  /* #95: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #96: output[0][18] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+90);
  /* #97: @2 = input[0][38] */
  casadi_copy(arg[0] ? arg[0]+133 : 0, 2, w2);
  /* #98: @3 = fxDisc(@1, @2) */
  arg1[0]=w1;
  arg1[1]=w2;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #99: @1 = input[0][39] */
  casadi_copy(arg[0] ? arg[0]+135 : 0, 5, w1);
  /* #100: @3 = (@3-@1) */
  for (i=0, rr=w3, cs=w1; i<5; ++i) (*rr++) -= (*cs++);
  /* #101: output[0][19] = @3 */
  if (res[0]) casadi_copy(w3, 5, res[0]+95);
  return 0;
}

int qp_h(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

void qp_h_incref(void) {
}

void qp_h_decref(void) {
}

int qp_h_n_in(void) { return 2;}

int qp_h_n_out(void) { return 1;}

const char* qp_h_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* qp_h_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const int* qp_h_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const int* qp_h_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

int qp_h_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 68;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
